apiVersion: v1 
kind: Pod
metadata:
  name: my-container-task6
spec:
  hostNetwork: true
  containers:
    - name: task5image
      image: ebaroks/imagetask6
      command: ['/app/script.sh']
      #command: ["/bin/sh","-c"]
      #args: ["bin/demo /tmp/task5.yaml username; trap : TERM INT; sleep infinity & wait"]
      args: ['/tmp/task5.yaml', 'username']
      # envFrom:
      # - configMapRef:
      #     name: task6 
      volumeMounts:
      - name: configvolume
        mountPath: /tmp/task5.yaml
        subPath: task5.yaml 
      env:
      - name: CONFIG_USERNAME
        valueFrom: 
          secretKeyRef:
            name: task7-secret
            key: username
      - name: CONFIG_PASSWORD
        valueFrom: 
          secretKeyRef:
            name: task7-secret
            key: password     
  volumes:
    - name: configvolume
      configMap:        
        name: task6 